// ./features/glimsPrefixes.js

// 1. Onze basis datatypes (die staan niet in de GLIMS objectenlijst)
const basePrefixes = {
    "string": ["s", "sl", "stl"], 
    "integer": ["i"],
    "logical": ["l", "b"],
    "fractional": ["f", "d"],
    "date": ["d"],
    "datetime": ["dt"],
    "time": ["tm"]
};

// 2. De ruwe GLIMS lijst (Kopieer en plak je lijst hier gewoon in!)
const rawGlimsList = `
AccessList	acl
AccessProfile	acp
Account	acnt
AccountingClass	accl
AccountingClassAssignment	acas
AccuracyCheck	acc
AccuracyCheckTemplate	acct
Action	actn
Allele	alle
AlleleEplet	alep
AllelicState	alls
AllelicStateDescription	ml53
Animal	anml
Antibiotic	ab
AntibioticAtuRule	abar
AntibioticConversionRule	abcr
AntibioticDescription	ml82
AntibioticPanel	abp
AntibioticPanelMember	abpm
AntibioticPanelUsage	abpu
AntibioticRelevance	abrl
AntibioticResult	abrs
AntibioticResultDefault	abrd
Antigen	anti
Approach	appr
ApproachActivity	apac
ApproachActivityAction	apaa
ApproachPlan	aprp
ApproachPlanUsage	appu
ApproachRequest	arqt
ApproachTransition	aprt
Archive	larc
ArchivePart	arcp
ArchivePartDescription	ml17
ArchiveSubdivision	larl
AssessmentMethod	amtd
AssessmentMethodCode	amc
AssessmentMethodStatus	amts
AssessmentMethodValueList	amvl
AssessmentReagentConsumption	amrc
AttributeTransfusionRule	atfr
Balance	bal
BAMAction	bact
BAMConfiguration	bcnf
BamCount	bmcn
BamCounter	bamc
BamCounterSet	bmcs
BamCounterSetCounter	bcsc
BamCounterSetCounterTitle	ml57
BamCounterSetName	ml49
BAMCounterState	bcst
BamCounterTitle	ml51
BAMOrder	bord
BAMResult	brsl
BAMRun	brun
BAMTat	btat
Bank	bnk
BankAccount	bnkc
BankAccountHolder	bach
BankMandate	bkmn
BillingCategory	bcat
BillingCode	bc
BillingCodeAssignment	bcas
BillingCodeGroup	bcg
BillingCodeGroupMember	bcgm
BillingCodxtrnalDscripti	ml63
BillingDocumentOutPrint	bdop
BillingDocumentTemplate	bdtp
BillingItem	bit
BillingRule	bru
BillingRuleLine	brl
BillingRuleLineInput	brli
BillingRuleLineOutput	brlo
BloodAttribute	blat
BloodBag	bbag
BloodBagAntigen	bgag
BloodBagAttribute	bbat
BloodBagTyping	bbtp
BloodBagTypingAntigen	btag
BloodDonorRule	bldr
BloodProduct	blpr
BloodProductDescription	ml95
BloodProductOrderAdvice	bpoa
BloodProductSpecification	bspc
BloodProperty	bprp
BloodRecipientType	blrt
BloodRequestable	blrb
BloodSelection	bsel
BloodSpecificationCode	bpsc
bt_ActualFunctionParameter	afp
bt_ActualFunctionParameterSet	afps
bt_ActualQueryParameter	aqp
bt_ActualQueryParameterSet	aqps
bt_Command	cmnd
bt_SchedulerAssignment	scas
bt_Task	task
bt_TaskStatus	tsks
Budget	budg
BudgetCharge	buch
BudgetClass	bucl
BudgetClassAssignment	buca
BudgetDefinition	budf
BudgetInvoice	buiv
BudgetItem	buit
Carrier	carr
CarrierTest	cart
CashRegister	rgst
CashRegisterMovement	rgtm
CashRegisterSession	rgts
Choice	chc
ChoiceDescription	ml07
ChoiceList	chcl
Chromosome	chrm
ChromosomeRegion	chrr
ClinCase	cca
ClinCaseOrder	ccao
ClinConsultation	clc
ClinConsultationForm	clcf
ClinConsultationParticipant	clcp
ClinConsultationType	clct
ClinConsultationTypeForm	cltf
ClinicalGrading	clgr
ClinicalGradingDescription	ml65
ClinicalStatus	clst
ClinicalStatusDescription	ml44
CNVGene	cnvg
Code	code
CodeDescription2	ml21
CodeSet	cset
CodingSystem	csys
CodingSystemDescription	ml20
Company	cmpn
Complaint	cplt
ComplaintCategory	cplc
ComplaintLog	cplg
Consult	cns
ConsultLog	cnsl
ConsultStatus	cnss
ConsultType	cnst
Contact	cntc
Contract	cntr
ContractType	cntp
Conversion	cnv
CopyNumberVariant	cpnm
CorrespondClassDescriptio	ml25
Correspondent	crsp
CorrespondentClass	crcl
CorrespondentGroup	crgp
CorrespondentGroupMember	crgm
CorrespondentLog	crlg
CostLocation	cstl
Country	cnty
CountryName	ml68
CrossInfection	crif
DefaultCode	dcde
DefaultReport	dfrp
Delivery	dlv
DeltaNorm	dnrm
Department	dept
DepartmentGroup	dptg
Diagnosis	diag
DiagnosisCode	dgc
DiagnosisCodeReportText	ml08
DiagnosisCodeSystem	dgcs
DilutionCode	dlc
Dimension	dim
Discount	disc
DiscountClass	dscl
DiscountCode	dscc
DiscountCodxtrnalDscripti	ml64
DiscountFormula	dscf
DiscountGroup	dsgr
DiscountGroupAssignment	dsga
DiscountGroupDescription	ml04
DiscountGroupFormula	dsgf
Disorder	dsrd
DisorderAssociation	dsra
DisorderDescription	ml48
DisorderGene	dsgn
DNAChangeType	dnch
DNAChangeTypeDescription	ml30
DomainAlias	doma
DomainAuthorization	dmnt
EmployeeAssignment	empa
EmployeeAssignmentTemplate	emat
Encounter	enct
EncounterType	entp
Eplet	eplt
ExecutingClass	excl
ExternalApplication	exap
ExternalBloodStorage	exbs
Family	fml
FamilyCondition	fmlc
FamilyMember	fmlm
FamilyMemberCondition	fmcd
FamilyPair	fmlp
FamilyPregnancy	fmpr
FinancialShipment	fshp
FinancialShipmentEntry	fshe
FinancialTransaction	ftr
Financing	fnc
Firm	firm
FirmAccount	frma
Fund	fnd
FundType	fndt
Gain	gn
GenderCheck	gndr
Gene	gne
GeneRegion	gnrg
GeneticExam	gnte
GeneticProcedure	gntp
GeneticProcedureDescriptio	ml26
GeneticProcedureMaterial	gntm
GeneticRequestable	gntr
GeneticResultDetail	gnrd
GeneTranscript	gntt
gp_Attachment	att
gp_AttachmentCategory	atc
gp_AttachmentCategoryLabel	mm13
gp_ConversionInfo	cvi
gp_DataChange	dtch
gp_DbVersion	dbv
gp_Event	evt
gp_EventHandler	evth
gp_FieldHistory	fdhs
gp_FileBlob	blb
gp_Holiday	hday
gp_Language	lng
gp_LargePreference	lprf
gp_License	lcns
gp_LicenseUser	lusr
gp_MailMessage	mlms
gp_MailReceipt	mlrc
gp_Preference	pref
gp_QueueProcessor	qprc
gp_QueueProcessorStatus	qprs
gp_RESTSession	rses
gp_Sequence	seq
gp_Service	svc
gp_ServiceCluster	scl
gp_ServiceClusterDescripti	mm17
gp_ServiceClusterFailover	sclf
gp_ServiceGroup	svg
gp_ServiceGroupDescription	mm08
gp_ServiceHost	svh
gp_ServiceHostDescription	mm18
gp_ServiceStatus	svcs
gp_Session	sess
gp_SessionDevice	sdev
gp_Site	gsit
gp_SiteAttribute	satt
gp_SiteAttributeCategory	sact
gp_SiteAttributeValue	satv
gp_SiteFunction	sfn
gp_SiteFunctionCall	sfc
gp_SpeedTest1	spt1
gp_SpeedTest2	spt2
gp_SpeedTestHistory	sth
gp_SpeedTestMonitor	spm
gp_Text	txt
gp_TextText	ml41
gp_Translator	trl
gp_TranslatorStatus	trls
gp_UniqueLicenseUser	unlu
gp_UpgradePlan	upgp
gp_UpgradeRegistration	uprg
gp_UpgradeStep	upgs
gp_UserAction	usac
HCProvider	hcpr
HCProviderAvailability	havl
HCProviderResponsibility	hrsp
HealthOffice	hoff
HLAAntibody	hab
HLAAntigen	hag
HLAExam	hlxm
HLAProcedure	hlpr
HLAProcedureDescription	ml69
HLAProcedureMaterial	hlpm
HLAPrsnAbScreeningResult	pasc
HLAPrsnAgTypingResult	pagt
HLARequestable	hlrb
HLAScreeningResult	scrr
HLATypingResult	typr
HospitalEmployee	hemp
HospitalInfection	hifc
hp_DateTimeSection	hpds
hp_HomePage	hpge
hp_HomePageDescription	mm01
hp_Section	hpsc
hp_SectionDescription	mm02
hp_SectionLabel	mm03
hp_Shortcut	hpsh
hp_ShortcutLabel	mm04
hp_ShortcutSection	hpss
hp_ShortcutTooltip	mm05
hp_WebBrowserSection	hpbs
ICDAdvicePathogen	icdp
ICDAdviceResistanceRule	icdr
ICDAdviceResistanceRuleLine	icrl
ICDAdviceRule	icda
ICDAdviceSpecies	icds
ICDAdviceSpeciesPathogen	icsp
ICDAdviceSpeciesResistRule	icsr
ICDAdviceText	icdt
Identification	idnt
IdentificationType	idtp
IdentificatTypeDescription	ml23
Infection	ifc
InheritancePattern	inhr
InheritanPatternDescripti	ml58
Institution	inst
InsuranceProduct	inpr
Invoice	inv
InvoiceGroupingType	igt
InvoiceItem	iit
InvoiceRejectionType	irt
InvoiceRejectionTypeAction	irta
InvoiceSummary	invs
InvoiceSummaryReminder	isr
io_Message	msg
io_MessageNode	msgn
Isolation	isol
IsolationAppraisal	isap
IsolationAppraisalText	ml16
IsolationHistory	isoh
IsolationSequence	iseq
IsolationSequenceType	ist
IsolationTest	isot
IsolationTestOutput	isto
IssuerCombination	icmb
ItemStorage	spst
IvocRjctonTypxtrnlDscrpt	ml09
Lab	lab
lg_Entry	lge
lg_Log	log
lg_Type	lgt
ListDetailType	lstd
ListType	lstt
Locus	lcs
LocusGroup	lcsg
LocusGroupMember	lcgm
LocusGroupType	lcgt
LocusReagent	lcrg
LocusResult	lcsr
Lot	lot
MasterMix	mstm
MasterMixItem	mmi
MasterMixRecipe	mmr
MasterMixRecipeInstruction	ml60
MasterMixRecipeItem	mmri
Material	mat
MaterialContainerUsage	mtcu
MaterialDescription	ml18
MaterialGroup	matg
MaterialGroupMember	mgm
MaterialInput	mati
MaterialOutput	mato
MaterialRequestable	mtrb
MaterialValidityRule	mavr
MaterialVariable	matv
MaterialVariableChoice	mtvc
MaterialVariableResolver	mtvr
MatrialVariablChoicValu	ml86
MBQCLot	mqcl
MBQCMaterial	mqcm
MBQCResult	mqcr
MBQCTest	mqct
MBReagent	mrgt
MBReagentLot	mrgl
Medium	mdm
MediumPanel	mdmp
MediumPanelMember	mpm
MediumTest	mdt
MediumTestUsage	mdtu
MediumUsage	mdu
MicrobiologyAction	mcra
MicrobiologyProcedure	mcrp
MicrobiologyRequestable	mcrb
MicrobiolProcdurDscripti	ml97
MicroOrganism	morg
MicroOrganismDescription	ml96
MicroOrganismTest	mot
MicroOrganismTestInput	moti
MicroOrganismTestMethod	motm
MicroOrganismTestOutput	moto
MicroOrganismTestUsage	motu
MicroScreenSyncDevice	mcrs
MolcularClassificDscripti	ml61
MolecularClassification	mlcl
Municipality	mncp
NCContext	nccn
NCCorrectionChoice	nccc
NCCorrectionChoiceList	nccl
NCEventLog	ncel
NCType	nctp
NnCnfrmtCrrctChcDscrpt	ml43
Nonconformity	nc
NonconformiTypeDescription	ml38
NonconformityTypeAdvice	ml42
Norm	norm
NormReferenceType	nrtp
NormReferenceTypeDescripti	ml28
Object	obj
ObjectAttribute	obja
ObjectAttributeDescription	ml98
ObjectAttributeHistory	obah
ObjectTemplate	objt
om_Barcode	ombc
om_Category	omcg
om_Container	omcr
om_Control	omcl
om_Form	omfm
om_Mark	ommk
om_Prompt	ompm
Order	ord
OrderAppraisal	ml55
OrderIdentifier	orid
OrderRecurrence	orec
OrderSet	os
OrderTodoItem	otdi
OrderTodoList	otdl
Organization	org
Package	pckg
PackageAudit	pcka
PackageItem	pcki
PackageItemAudit	pia
PanelMember	panm
PanelRequestable	pnrb
PathologyExam	ptex
PathologyProcedure	ptpr
PathologyRequestable	ptrb
PatientDisorder	pntd
PatientGeneToTest	pgtt
Payment	pmnt
PaymentAgreement	paya
PaymentInfo	pinf
Person	prsn
PersonAntigen	prag
PersonGeneticDisorder	psgd
PersonHLAAntibody	phab
PersonHLAAntigen	phag
PersonLab	plab
PersonMedicalRecord	prmr
PersonNMRInfo	pnmr
PersonRelation	prel
PersonSearchName	psn
PhoneLog	phlg
PlanActivity	plnc
PlanLocus	plnl
PlanTransition	plnt
Plate	plt
PlateItem	plti
PlateType	pltt
PlateTypeDescription	ml56
PlateTypeUsage	pltu
Policy	plcy
PolicyClause	plcc
PolicyName	plcn
Postleitzahl	plz
PriceCode	prcc
PriceFormula	prcf
PriceList	prcl
Procedure	proc
ProcedureData	prcd
ProcedureGroup	prg
ProcedureGroupMember	prgm
ProcedureInput	prci
ProcedureOutput	prco
ProcedureRequestable	pcrb
Product	prdc
ProductDelivery	pdlv
ProductLot	prdl
ProductSpecification	pspc
ProductType	ptp
ProductUsage	pdus
Property	prop
PropertyClass	pcla
PropertyClassification	pcl
PropertyClassificationNode	pcln
PropertyClassificNodeLabel	ml54
PropertyDescription	ml27
PropertyInput	prpi
PropertyLoincCode	prlc
PropertyOutput	prpo
PropertyRequestable	pprb
PropertyWeight	prpw
ProteinChangeType	prtn
ProteinChangeTypeDescripti	ml29
Provision	prov
PurchaseItem	pchi
PurchaseOrder	pcho
PurchaseOrderInvoice	prch
QCAudit	qcau
QCAuditResult	qcar
QCCheck	qcc
QCChoice	qcch
QCChoiceDescription	ml19
QCChoiceList	qccl
QCLot	qcl
QCMaterial	qcmt
QCPopulation	qcp
QCSchedule	qcs
Rack	rck
RackType	rckt
RackUsage	rcku
Reagent	rgt
ReagentLot	rgtl
ReagentUsage	rgtu
Referral	rfrl
ReimbursementClass	rbcl
Report	rprt
ReportColumn	rprc
ReportGroup	rprg
ReportNMRInfo	rnmr
ReportPage	rprp
ReportTemplate	rptp
ReportTemplateActionHeader	ml13
ReportTemplateNormHeader	ml12
ReportTemplateSOPheader	ml14
ReportTemplateUnitHeader	ml11
ReportTemplateValueHeader1	ml22
Request	rqst
Requestable	rqbl
RequestableVariable	rblv
RequestCharge	rqch
RequestCode	rqcd
RequestedCode	rqsc
RequestForm	rqf
RequestFormAssignment	rqfa
RequestFormNode	rqfn
ReservedWell	rswl
Responsibility	rsp
ResponsibilityDelegation	rspd
ResponsibilityHCProvider	rspn
Result	rslt
ResultCode	rstc
ResultInput	rsti
ResultOutput	rsto
ResultReagentUsage	rsru
ResultText	rtxt
Route	rt
RouteProcedure	rp
rp_ExternalTemplate	rpxt
rp_ExternalTemplateComment	mm15
rp_Printer	rpp
rp_PrinterAssignment	pras
RportTmplatDscriptiHadr	ml15
RportTmplatMatrialHadr	ml10
RportTmplatPrviousDatHadr	ml06
RportTmplatPrviousValuHadr	ml05
RportTmplatShortValuHadr	ml03
RportTmplatValidatorHadr	ml01
RportTmpltShortProprtyHdr	ml02
rt_Field	rtfd
rt_FormalFunctionParameter	ffp
rt_FormalQueryParameter	fqp
rt_Function	rtfn
rt_Index	rtix
rt_Message	rtmg
rt_MessageText	rtmt
rt_Query	rtqr
rt_Reference	rtrf
rt_Table	rttb
sc_ADDSDomain	adds
sc_AuditEvent	adtv
sc_DatabaseUser	dusr
sc_Domain	dmn
sc_DomainDescription	mm16
sc_DomainRoleAlias	dra
sc_FieldPrivilege	fdpv
sc_FunctionParamSetPrivilege	fpsp
sc_FunctionPrivilege	fnpv
sc_HashiCorpVault	hcv
sc_LDAPDomain	ldap
sc_LoginFailure	lgfl
sc_OIDCDomain	oidc
sc_OIDCDomainDescription	mm19
sc_OIDCDomainOption	odcd
sc_OIDCUserAlias	oiua
sc_Privilege	priv
sc_PrivilegeDescription	mm12
sc_PrivilegeLabel	mm11
sc_Resource	res
sc_ResourcePrivilege	rspv
sc_Role	role
sc_RoleDescription	mm10
sc_RoleName	mm09
sc_RolePrivilege	ropv
sc_SiteAttributePrivilege	satp
sc_TablePrivilege	tbpv
sc_User	usr
sc_UserGroup	usrg
sc_UserGroupAssignment	usra
sc_UserPrivilege	upv
sc_UserRoleAssignment	rola
sc_Vault	vlt
sc_WebDomain	webd
sc_WindowsServiceAccount	wsa
SequenceVariant	sqnc
SortingZone	srtz
SortingZoneGroup	srzg
sp_Domain	sdmn
SpcfcStCbtCrossBloodnvTxt	ml24
Specialism	spec
SpecificSite	ssit
Specimen	spmn
SpecimenAudit	spau
SpecimenCollectionInfo	spmc
SpecimenContainerCap	spcc
SpecimenContainerDefinition	spcd
SpecimenContainerType	spct
SpecimenExternalComment	ml59
SpecimenHandling	spmh
SpecimenHandlingDescriptio	ml37
SpecimenIdentification	spid
SpecimenIdentificationType	spit
SpecimenInput	spmi
SpecimenOutput	spmo
SpecimenPool	spmp
SpecimenPoolMember	spmm
SpecimenSortAudit	ssa
SpecimenSortEvent	sse
SpecimenSortingTarget	sst
SpecimenVariable	spmv
st_StatisticCell	stce
st_StatisticColumn	stcl
st_StatisticRow	strw
st_StatisticSet	stst
st_StatisticTable	sttb
StaffMeetingOrder	smo
Station	stn
StationAssignment	stna
StationEventCode	stec
StationFlag	snfg
StationGroup	stg
StationLog	stlg
StationRun	srun
StationStatus	stns
StationUser	stnu
Stay	stay
Stock	stck
Study	stdy
StudyEpisode	stde
StudyObject	stdo
StudySubject	stds
Tariff	tar
Task	tsk
TicketBookRange	tbr
Tour	tour
TourMember	trmb
TransplanProductDescripti	ml66
Transplant	trnp
TransplantProduct	trns
TransplantRegistration	trre
TransplantRegistrationHLAExam	trrh
TransplantRegistrationStatus	trrs
TransplantRequestable	trrb
TransplantSelection	trse
TrendCheck	trc
TrendCheckTemplate	trct
TriggCheck	tgc
TriggCheckHistory	tgch
TriggCheckTemplate	tgct
TrnsplnRgstrtSttusDscrpt	ml67
um_Option	optn
um_OptionLabel	ml45
um_QuickAccessToolbar	qatb
um_QuickAccessToolbarGroup	qatg
um_QuickAccessToolbarItem	qati
um_QuickAccessToolbarMenuItem	qami
um_QuickAccessToolbarRibItem	qari
um_Ribbon	rbbn
um_RibbonDescription	mm07
um_RibbonGroup	rgrp
um_RibbonGroupLabel	ml34
um_RibbonItem	ritm
um_RibbonItemLabel	ml39
um_RibbonItemTooltip	ml40
um_RibbonTab	rtab
um_RibbonTabAssignment	rtba
um_RibbonTabLabel	ml33
um_Sidebar	sbar
um_SidebarDescription	mm06
um_SidebarGroup	sbgr
um_SidebarGroupLabel	ml35
um_SidebarGroupToolTip	ml36
um_SidebarItem	sbit
um_SidebarItemLabel	ml50
um_SidebarItemTooltip	ml52
um_Tool	tool
um_ToolbarButton	tbbt
um_ToolBarButtonHelpText	ml47
um_ToolBarButtonLabel	ml46
um_ToolFunctionPath	tlfp
um_ToolLabel	ml31
um_ToolLayout	tllt
um_ToolToolTip	ml32
Unit	unit
UnitDescription	ml99
UnknownObject	uobj
ux_Style	stl
ux_StyleDescription	mm14
ux_StyleRule	stlr
ux_StyleSheet	stls
Variant	vrnt
VariantResult	vrnr
VariantResultDetail	vrrd
VATCode	vatc
VATCodeDescription	ml62
VATRate	vatr
Vertragsarztnummer	sdav
w_ActionsOfStation	wact
w_AntibioticComment	antb
w_ArchivedOrder	aord
w_BankAccount	bnka
w_BarCode	wbc
w_BillingAssessment	ba
w_BillingCodeInstance	bci
w_BillingDocumentDiscountLine	bddl
w_BillingDocumentLine	bdln
w_BillingDocumentVATLine	bdvl
w_BillingRuleInstance	bri
w_BloodBag	wbbg
w_BloodSelection	wbls
w_BudgetContext	bucn
w_Carrier	wcar
w_ClinicalConsultation	wclc
w_CorrespondentFax	crrs
w_Delivery	dlvr
w_DeliveryCharge	dlch
w_ExtendedResult	were
w_ExternalPatient	extp
w_ExternalPaymentAgreement	expa
w_Family	wfml
w_GeneticExam	wgen
w_HCProvider	whcp
w_IcdSd	icd
w_Identification	pid
w_IncompleteResult	wire
w_MBQCResult	wmqr
w_MemberInstance	mi
w_Order	ordr
w_OrderConsultation	worc
w_PanelInstance	pi
w_Patient	pat
w_Phone	phn
w_Product	wprc
w_ProductBarCode	pbc
w_ProductCollection	wpcl
w_PropertyDepartment	wprd
w_QCPopulation	wqcp
w_QuarterlyBillingStat	qbs
w_ReimbursementClause	rmbc
w_ReportColumn	wrc
w_ReportItem	wri
w_ReportPage	wrp
w_ReportRow	wrr
w_Request	wrq
w_RequestCode	wrqd
w_Result	orsl
w_Sample	smpl
w_StationEvent	stne
w_StatisticsHeader	stts
w_StayChange	stch
w_SubContractContext	sbcn
w_TableActivity	tbla
w_TapeBorderel	tpbr
w_TextUsage	txtu
w_UrgentOrder	wurg
w_UserDatabaseActivity	uda
w_Visit	vst
w_WorkIsolation	wiso
w_WorkList	wwrk
w_WorkOrder	word
w_WorkOrderResult	wors
Ward	ward
wd_WatchdogConfiguration	wdc
wd_WatchdogStatus	wds
WestgardCheck	wgc
WestgardCheckTemplate	wgct
WorkList	wlst
WorkListEntry	wle
WorkListExportLayout	wlel
WorkListTemplate	wlt
WorkListTemplateAssignment	wlta
WorkListTemplateEntry	wlte
WorkListTemplateGroup	wltg
WorkListTemplateGroupMember	wtgm
WorkListTemplateItem	wlti
WorkListTemplateLayout	wltl
WorkListTemplateLocus	wrkl
WorkListTemplateVariant	wrkv
WorkPlace	wrkp

`;

// 3. De Auto-Parser: Bouwt de dictionary razendsnel op
const PREFIXES = { ...basePrefixes };

rawGlimsList.trim().split('\n').forEach(line => {
    // Knip de regel op bij de tab of spaties
    const parts = line.trim().split(/\s+/);
    
    // Als we netjes een Naam en een Korte Naam hebben:
    if (parts.length === 2) {
        const typeName = parts[0].toLowerCase();
        const prefix = parts[1].toLowerCase();
        
        // Voeg toe aan de dictionary! (bijv. PREFIXES["accesslist"] = ["acl"])
        PREFIXES[typeName] = [prefix];
    }
});

module.exports = PREFIXES;